#
# User configuration sourced by interactive shells
#

# Set powerlevel10k dir
POWERLEVEL10K_INSTALLATION_PATH=~/.zim/modules/prompt/external-themes/powerlevel10k/powerlevel10k.zsh-theme

# Define zim location
export ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim

# Start zim
[[ -s ${ZIM_HOME}/init.zsh ]] && source ${ZIM_HOME}/init.zsh

# Lines configured by zsh-newuser-install
HISTFILE=~/.zhistfile
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory autocd notify
bindkey -e
# End of lines configured by zsh-newuser-install

# Source files if they exist
function zsourcefile {
    [[ -s "$1" ]] && source $1
}
## Functions and aliases
zsourcefile ${HOME}/.zfunctions
zsourcefile ${HOME}/.zaliases
## Misc files
zsourcefile ${HOME}/.chef/functions.zsh
zsourcefile ${HOME}/.fzf.zsh
zsourcefile /usr/local/share/chtf/chtf.sh

# Use Neovim as default editor
export EDITOR=nvim

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Ready for Go
export GOPATH=~/go

# Set Path
export PATH=~/bin:$GOPATH/bin:$PATH
